# /********************************************************************************
# * Copyright (c) 2024 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: Create Draft Release

on:
  workflow_dispatch: # input version manually. Overrides push tag
    inputs:
      vss-version:
        description: "Release version, eg:latest, 4.2, 4.2rc0"
        required: true
        default: "0.0.0"

  # As of today trigger only manually
  #push:
  #  tags:
  #    - "*.*.*"

# Needed if GITHUB_TOKEN by default do not have right to create release
permissions:
  contents: write
  packages: write

jobs:
  call_kuksa_databroker_build:
    uses: ./.github/workflows/buildcheck.yml
    with:
      vss-version: ${{ inputs.vss-version }}

  create_release:
    runs-on: ubuntu-latest
    needs:
      [
        call_kuksa_databroker_build
      ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts
          # Only packed binaries shall start with "databroker"
          # As of now do not upload separate dash and third party reports
          pattern: vss.*
          merge-multiple: true
      - name: Display structure of downloaded files
        run: |
             ls -R build-artifacts

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/'
        with:
          draft: true
          tag_name: KUKSA Databroker ${{ needs.get_version.outputs.version }}
          fail_on_unmatched_files: true
          files: |
            build-artifacts/*
